global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
      monitor: 'dashboard'


rule_files:
  - /etc/prometheus/rules/*.rules

scrape_configs:  
  - job_name: 'mongo'
    consul_sd_configs:
      - server: '10.20.70.36:8500'
        tags: ['mongo-exporter'] 
